export enum OnboardingStep {
  ACCOUNT_SETUP = 'ACCOUNT_SETUP', 
  ORG_SETUP = 'ORG_SETUP', 
  BILLING_CONTACT = 'BILLING_CONTACT', 
  PLAN_SELECTION = 'PLAN_SELECTION', 
  INVITE_MEMBERS = 'INVITE_MEMBERS', 
  COMPLETED = 'COMPLETED', 
}